config/routes.rb
Rails.application.routes.draw do
  resources :tweets
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "tweets#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

end

app/models/tweet.rb
class Tweet < ApplicationRecord
    include PgSearch::Model

    pg_search_scope :search_full_text, against: {
        username: 'A',
      }
    
    validates :username, :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[ show edit update destroy ]

  # GET /tweets or /tweets.json
  def index

    @tweets = Tweet.all.paginate(page: params[:page], per_page: 5)

    if params[:query_text].present?
      
      @tweets = @tweets.search_full_text(params[:query_text])
      
    end

  end

  # GET /tweets/1 or /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets or /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to tweet_url(@tweet), notice: "Tweet fue agregado con exitosamente." }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to tweet_url(@tweet), notice: "Tweet fue actualizado con exitosamente." }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    @tweet.destroy

    respond_to do |format|
      format.html { redirect_to tweets_url, notice: "Tweet fue eliminado con exitosamente." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:username, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <div class="container">
  
    <%= yield %>
  </div>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/0e5993ce45.js" crossorigin="anonymous"></script>
  </body>
</html>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet) do |form| %>
  <% if tweet.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
        <% tweet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :username, style: "display: block" %>
    <%= form.text_field :username %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tweets/_tweet.html.erb
<div id="<%= dom_id tweet %>">

  <p>
    <strong>Usuario:</strong>
    <%= tweet.username %>
  </p>

  <p>
    <strong>Descripción:</strong>
    <%= tweet.description %>
  </p>

</div>

app/views/tweets/edit.html.erb
<nav class="navbar bg-primary" data-bs-theme="dark">
  <div class="container-fluid">
    <a class="navbar-brand"><i class="fa-brands fa-twitter fa-flip" style="color: #ffffff;"></i></a>
    <h1 class="twitt-word">Editar Twitt</h1>
    <form class="d-flex" role="search">      

    <p style="color: white"><%= notice %></p>
    </form>
  </div>
</nav>




    <div class="card text-center">

      <div>
        <div class="d-flex justify-content-around p-2">
            <div class="d-flex justify-content-around">

                <%= render "form", tweet: @tweet %>
                <br>
                
            </div>
        
        </div>
          <div class="d-flex justify-content-around">


            <%= link_to "Ver twitt", @tweet, class:"btn btn-primary gap-0 row-gap-3"  %>
            <%= link_to "Volver a twitts", tweets_path, class:"btn btn-primary gap-0 row-gap-3"  %>

          </div>
      </div>
    </div>

app/views/tweets/index.html.erb
<p style="color: green"><%= notice %></p>



<nav class="navbar bg-primary" data-bs-theme="dark">
  <div class="container-fluid">
    <a class="navbar-brand"><i class="fa-brands fa-twitter fa-flip" style="color: #ffffff;"></i></a>
    <h1 class="twitt-word">Twitter</h1>
    <form class="d-flex" role="search">      
      <%= form_with url: tweets_path, method: :get do |form| %>
        <%= form.text_field :query_text, class:"input", onChange: '
        this.form.requestSubmit()', value: params[:query_text]%>
      <% end %>
    </form>
  </div>
</nav>


<div id="tweets ">
  <% @tweets.each do |tweet| %>
    <div class="card text-center">
        
        <%= render tweet %>
        <p>
          <%= link_to "Ver twitt", tweet, class:"btn btn-primary" %>
        </p>
    </div>
  <% end %>
</div>


<div class="d-flex justify-content-around">

  <%= link_to "Nuevo twitt", new_tweet_path, class:"btn btn-primary" %>

  <%= will_paginate @tweets, renderer: WillPaginate::ActionView::BootstrapLinkRenderer%>
</div>

app/views/tweets/new.html.erb
<nav class="navbar bg-primary" data-bs-theme="dark">
  <div class="container-fluid">
    <a class="navbar-brand"><i class="fa-brands fa-twitter fa-flip" style="color: #ffffff;"></i></a>
    <h1 class="twitt-word">Nuevo Twitt</h1>
    <form class="d-flex" role="search">      

    <p style="color: white"><%= notice %></p>
    </form>
  </div>
</nav>


    <div class="card text-center">
        <%= render "form", tweet: @tweet %>
        <br>

      <div>
        <div class="d-flex justify-content-around p-2">
            <div class="d-flex justify-content-around">

                <%= link_to "Volver a twitts", tweets_path, class:"btn btn-primary" %>

            </div>
        
        </div>
      </div>
    </div>

app/views/tweets/show.html.erb
<nav class="navbar bg-primary" data-bs-theme="dark">
  <div class="container-fluid">
    <a class="navbar-brand"><i class="fa-brands fa-twitter fa-flip" style="color: #ffffff;"></i></a>
    <h1 class="twitt-word">Twitter</h1>
    <form class="d-flex" role="search">      

    <p style="color: white"><%= notice %></p>
    </form>
  </div>
</nav>

    <div class="card text-center">
        
      <%= render @tweet %>

      <div>
        <div class="d-flex justify-content-around p-2">
        
          <%= link_to "Editar twitt", edit_tweet_path(@tweet), class:"btn btn-primary" %>
          <%= link_to "Volver a twitt", tweets_path, class:"btn btn-primary" %>

          <%= button_to "Eliminar twitt", @tweet, method: :delete, class:"btn btn-primary gap-0 row-gap-3" %>
        
        </div>
      </div>
    </div>